language: node_js
node_js:
- stable
sudo: false
script:
- npm install
- npm test
deploy:
  provider: npm
  email: manager@mathjax.org
  api_key:
    secure: vw9iaITN8Nr8rXkkoWoY61Iu79b6U06yHoFAdcefTOeUaPlbtjN/zXZ7DWp7XUm/MHcaZWHCJc25X6j7+t8SsOGO0RyR6rLxPVACLvRZWbOwCpgOIRH37QtJnFWYudpiaUqmMkyAHL/XZv3OpxugQGaRHyLWYwct9oUksjbDw45UWhynIj21/cSq2Vcp+bIY2n7Pbzb3XObBgIj8pxhHqsInhkfUiAGzqIuX6lRfKSgkuYREyMNG1fwFj1NaafRku2P/WtH/2Drv4MBQRKDAQPQtuz030eH3XjN2Fu/rSGfftsNAh4KSzvDF7VqXr27vYSMNTz2TfOvYrx1UgC8DPNc0X3vpTyIuSUR8fJ3M7hTpe3dukmKNYe+UJ3KO8CN5xd3q+U63LDjSXlw1YIr1Frj6py4utrqJVw++CkaJpDz/tx6oXROCukwe5VcGhpu5p3Zvjvi1LrN5+JYf+RrxEcNu/nC+8+gj6ZOttG596mEGVkFBE2TNoRxB96kfL4uINbJgZojmfoelZOdbEo2NiKTP2/yxcz0x7j4MFGdgRW1MIss6MKfKtkjdKjJeF+YE1CqtFwCAS6fNZNE3jEZRv0QWhpR3htqXhyLfsQPlYpn/8nFLOD/P5r9Es1uAcLElN5ioJ/79/UUcc6MML7gvbLVoFo60nRBlhwd813A9tao=
  on:
    tags: true
    repo: mathjax/MathJax-a11y
